### ISSUE TITLE
大佬，给你start了，能不能做个win版？

### ISSUE THREAD

**Issue by Rashhz** [qingjiuzys/titan-start#1]
win版也有docker，官方的脚本不好使，拜托你做一个

**Comment by qingjiuzys** [comment]
是这样的 win可以考虑按照vmware 后执行这个命令，我目前已经很多年没有使用win的电脑，也无法开发和调试win的脚本，希望你能理解。

**Comment by Rashhz** [comment]
好的，谢谢大佬
